server:
  port: 8080


spring:
  application:
    name: product-service

  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8087/
          jwk-set-uri: ${JWKS_URL}



eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
