server:
  port: 8081

spring:
  application:
    name: Order Service

  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8087/
          jwk-set-uri: http://localhost:8087/.well-known/jwks

db:
  hostname: localhost
  database: ecommerce
  username: ecommerce
  password: admin123

eureka:
  client:
    service-url:
      defaultZone: http://eureka:2222/eureka/
