server:
  port: 8081

spring:
  application:
    name: Order Service

  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8087/
          jwk-set-uri: http://localhost:8087/.well-known/jwks


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
