server:
  port: 8081

spring:
  application:
    name: order-service

  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8087/
          jwk-set-uri: ${JWKS_URL}


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
