version: '2.1'

services:
  postgresdb:
    build: storage/postgresdb
    ports:
      - 5433:5432

  discovery-server:
    build: system/discovery-server
    ports:
      - 2222:2222


  authentication-server:
    build: system/authentication
    env_file:
      - common.env
    environment:
      EXTRA_JAR_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8187
    ports:
      - 8087:8087
      - 8187:8187 #debug port
    depends_on:
      - postgresdb
      - discovery-server
    links:
      - postgresdb
      - discovery-server


  product-service:
    build: services/product
    env_file:
      - common.env
    environment:
      EXTRA_JAR_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8180
    ports:
      - 8080:8080
      - 8180:8180 #debug port
    depends_on:
      - postgresdb
      - discovery-server
      - authentication-server
    links:
      - discovery-server
      - postgresdb
      - authentication-server


  order-service:
    build: services/order
    env_file:
      - common.env
    environment:
      EXTRA_JAR_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8181
    ports:
      - 8081:8081
      - 8181:8181
    depends_on:
      - postgresdb
      - discovery-server
      - authentication-server
    links:
      - discovery-server
      - postgresdb
      - authentication-server



