version: '2.1'

services:
  postgresdb:
    build: storage/postgresdb
    ports:
      - 5433:5432

  discovery-server:
    build: system/discovery-server
    ports:
      - 2222:2222


  authentication-server:
    build: system/authentication
    command: mvn clean install
    environment:
      DISCOVERY_SERVER_URL: http://discovery-server:2222/eureka/
      DATABASE_HOST: postgresdb
      DATABASE_NAME: ecommerce
      DATABASE_SCHEMA: ecommerce
      DATABASE_PORT: 5432
      DATABASE_USER: ecommerce
      DATABASE_PASSWORD: admin123
      EXTRA_JAR_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8187
    ports:
      - 8087:8087
      - 8187:8187 #debug port
    depends_on:
      - postgresdb
      - discovery-server
    links:
      - postgresdb
      - discovery-server


  product-service:
    build: services/product
    command: mvn clean install
    environment:
      DISCOVERY_SERVER_URL: http://discovery-server:2222/eureka/
      JWKS_URL: http://authentication-server:8087/.well-known/jwks
      DATABASE_HOST: postgresdb
      DATABASE_NAME: ecommerce
      DATABASE_SCHEMA: ecommerce
      DATABASE_PORT: 5432
      DATABASE_USER: ecommerce
      DATABASE_PASSWORD: admin123
      EXTRA_JAR_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8180
    ports:
      - 8080:8080
      - 8180:8180 #debug port
    depends_on:
      - postgresdb
      - discovery-server
      - authentication-server
    links:
      - discovery-server
      - postgresdb
      - authentication-server


  order-service:
    build: services/order
    command: mvn clean install
    environment:
      DISCOVERY_SERVER_URL: http://discovery-server:2222/eureka/
      JWKS_URL: http://authentication-server:8087/.well-known/jwks
      DATABASE_HOST: postgresdb
      DATABASE_NAME: ecommerce
      DATABASE_SCHEMA: ecommerce
      DATABASE_PORT: 5432
      DATABASE_USER: ecommerce
      DATABASE_PASSWORD: admin123
    ports:
      - 8081:8081
    depends_on:
      - postgresdb
      - discovery-server
      - authentication-server
    links:
      - discovery-server
      - postgresdb
      - authentication-server



