server:
  port: 8087

spring:
  application:
    name: Authentication-Service

keystore:
  password: admin123
  keyPairAlias: ecommerce

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2222/eureka/