server:
  port: 8765

zuul:
  ignoredServices: '*'
  routes:
    authentication:
      serviceId: authentication-service
      path: /uaa/**
      sensitive-headers:

    products:
      serviceId: product-service
      path: /product/**
      sensitive-headers:

    orders:
      serviceId: order-service
      path: /order/**
      sensitive-headers:
